/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthedUnitsIndexRouteImport } from './routes/_authed/units/index'
import { Route as AuthedStockMovementsIndexRouteImport } from './routes/_authed/stock-movements/index'
import { Route as AuthedStockLocationsIndexRouteImport } from './routes/_authed/stock-locations/index'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedProductsIndexRouteImport } from './routes/_authed/products/index'
import { Route as AuthedPosTerminalIndexRouteImport } from './routes/_authed/pos-terminal/index'
import { Route as AuthedPaymentMethodsIndexRouteImport } from './routes/_authed/payment-methods/index'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as AuthedCustomersIndexRouteImport } from './routes/_authed/customers/index'
import { Route as AuthedCategoriesIndexRouteImport } from './routes/_authed/categories/index'
import { Route as AuthedUnitsAddRouteImport } from './routes/_authed/units/add'
import { Route as AuthedStockLocationsAddRouteImport } from './routes/_authed/stock-locations/add'
import { Route as AuthedProductsAddRouteImport } from './routes/_authed/products/add'
import { Route as AuthedPaymentMethodsAddRouteImport } from './routes/_authed/payment-methods/add'
import { Route as AuthedCustomersAddRouteImport } from './routes/_authed/customers/add'
import { Route as AuthedCategoriesAddRouteImport } from './routes/_authed/categories/add'
import { Route as AuthedUnitsEditIdRouteImport } from './routes/_authed/units/edit.$id'
import { Route as AuthedStockLocationsEditIdRouteImport } from './routes/_authed/stock-locations/edit.$id'
import { Route as AuthedStockLocationsDetailIdRouteImport } from './routes/_authed/stock-locations/detail.$id'
import { Route as AuthedProductsEditIdRouteImport } from './routes/_authed/products/edit.$id'
import { Route as AuthedProductsDetailIdRouteImport } from './routes/_authed/products/detail.$id'
import { Route as AuthedPaymentMethodsEditIdRouteImport } from './routes/_authed/payment-methods/edit.$id'
import { Route as AuthedPaymentMethodsDetailIdRouteImport } from './routes/_authed/payment-methods/detail.$id'
import { Route as AuthedCustomersEditIdRouteImport } from './routes/_authed/customers/edit.$id'
import { Route as AuthedCustomersDetailIdRouteImport } from './routes/_authed/customers/detail.$id'
import { Route as AuthedCategoriesEditIdRouteImport } from './routes/_authed/categories/edit.$id'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedUnitsIndexRoute = AuthedUnitsIndexRouteImport.update({
  id: '/units/',
  path: '/units/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStockMovementsIndexRoute =
  AuthedStockMovementsIndexRouteImport.update({
    id: '/stock-movements/',
    path: '/stock-movements/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedStockLocationsIndexRoute =
  AuthedStockLocationsIndexRouteImport.update({
    id: '/stock-locations/',
    path: '/stock-locations/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductsIndexRoute = AuthedProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPosTerminalIndexRoute = AuthedPosTerminalIndexRouteImport.update({
  id: '/pos-terminal/',
  path: '/pos-terminal/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPaymentMethodsIndexRoute =
  AuthedPaymentMethodsIndexRouteImport.update({
    id: '/payment-methods/',
    path: '/payment-methods/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCustomersIndexRoute = AuthedCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCategoriesIndexRoute = AuthedCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUnitsAddRoute = AuthedUnitsAddRouteImport.update({
  id: '/units/add',
  path: '/units/add',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStockLocationsAddRoute = AuthedStockLocationsAddRouteImport.update({
  id: '/stock-locations/add',
  path: '/stock-locations/add',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductsAddRoute = AuthedProductsAddRouteImport.update({
  id: '/products/add',
  path: '/products/add',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPaymentMethodsAddRoute = AuthedPaymentMethodsAddRouteImport.update({
  id: '/payment-methods/add',
  path: '/payment-methods/add',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCustomersAddRoute = AuthedCustomersAddRouteImport.update({
  id: '/customers/add',
  path: '/customers/add',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCategoriesAddRoute = AuthedCategoriesAddRouteImport.update({
  id: '/categories/add',
  path: '/categories/add',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUnitsEditIdRoute = AuthedUnitsEditIdRouteImport.update({
  id: '/units/edit/$id',
  path: '/units/edit/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStockLocationsEditIdRoute =
  AuthedStockLocationsEditIdRouteImport.update({
    id: '/stock-locations/edit/$id',
    path: '/stock-locations/edit/$id',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedStockLocationsDetailIdRoute =
  AuthedStockLocationsDetailIdRouteImport.update({
    id: '/stock-locations/detail/$id',
    path: '/stock-locations/detail/$id',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedProductsEditIdRoute = AuthedProductsEditIdRouteImport.update({
  id: '/products/edit/$id',
  path: '/products/edit/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductsDetailIdRoute = AuthedProductsDetailIdRouteImport.update({
  id: '/products/detail/$id',
  path: '/products/detail/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPaymentMethodsEditIdRoute =
  AuthedPaymentMethodsEditIdRouteImport.update({
    id: '/payment-methods/edit/$id',
    path: '/payment-methods/edit/$id',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedPaymentMethodsDetailIdRoute =
  AuthedPaymentMethodsDetailIdRouteImport.update({
    id: '/payment-methods/detail/$id',
    path: '/payment-methods/detail/$id',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedCustomersEditIdRoute = AuthedCustomersEditIdRouteImport.update({
  id: '/customers/edit/$id',
  path: '/customers/edit/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCustomersDetailIdRoute = AuthedCustomersDetailIdRouteImport.update({
  id: '/customers/detail/$id',
  path: '/customers/detail/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCategoriesEditIdRoute = AuthedCategoriesEditIdRouteImport.update({
  id: '/categories/edit/$id',
  path: '/categories/edit/$id',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/categories/add': typeof AuthedCategoriesAddRoute
  '/customers/add': typeof AuthedCustomersAddRoute
  '/payment-methods/add': typeof AuthedPaymentMethodsAddRoute
  '/products/add': typeof AuthedProductsAddRoute
  '/stock-locations/add': typeof AuthedStockLocationsAddRoute
  '/units/add': typeof AuthedUnitsAddRoute
  '/categories/': typeof AuthedCategoriesIndexRoute
  '/customers/': typeof AuthedCustomersIndexRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
  '/payment-methods/': typeof AuthedPaymentMethodsIndexRoute
  '/pos-terminal/': typeof AuthedPosTerminalIndexRoute
  '/products/': typeof AuthedProductsIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/stock-locations/': typeof AuthedStockLocationsIndexRoute
  '/stock-movements/': typeof AuthedStockMovementsIndexRoute
  '/units/': typeof AuthedUnitsIndexRoute
  '/categories/edit/$id': typeof AuthedCategoriesEditIdRoute
  '/customers/detail/$id': typeof AuthedCustomersDetailIdRoute
  '/customers/edit/$id': typeof AuthedCustomersEditIdRoute
  '/payment-methods/detail/$id': typeof AuthedPaymentMethodsDetailIdRoute
  '/payment-methods/edit/$id': typeof AuthedPaymentMethodsEditIdRoute
  '/products/detail/$id': typeof AuthedProductsDetailIdRoute
  '/products/edit/$id': typeof AuthedProductsEditIdRoute
  '/stock-locations/detail/$id': typeof AuthedStockLocationsDetailIdRoute
  '/stock-locations/edit/$id': typeof AuthedStockLocationsEditIdRoute
  '/units/edit/$id': typeof AuthedUnitsEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/categories/add': typeof AuthedCategoriesAddRoute
  '/customers/add': typeof AuthedCustomersAddRoute
  '/payment-methods/add': typeof AuthedPaymentMethodsAddRoute
  '/products/add': typeof AuthedProductsAddRoute
  '/stock-locations/add': typeof AuthedStockLocationsAddRoute
  '/units/add': typeof AuthedUnitsAddRoute
  '/categories': typeof AuthedCategoriesIndexRoute
  '/customers': typeof AuthedCustomersIndexRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/payment-methods': typeof AuthedPaymentMethodsIndexRoute
  '/pos-terminal': typeof AuthedPosTerminalIndexRoute
  '/products': typeof AuthedProductsIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/stock-locations': typeof AuthedStockLocationsIndexRoute
  '/stock-movements': typeof AuthedStockMovementsIndexRoute
  '/units': typeof AuthedUnitsIndexRoute
  '/categories/edit/$id': typeof AuthedCategoriesEditIdRoute
  '/customers/detail/$id': typeof AuthedCustomersDetailIdRoute
  '/customers/edit/$id': typeof AuthedCustomersEditIdRoute
  '/payment-methods/detail/$id': typeof AuthedPaymentMethodsDetailIdRoute
  '/payment-methods/edit/$id': typeof AuthedPaymentMethodsEditIdRoute
  '/products/detail/$id': typeof AuthedProductsDetailIdRoute
  '/products/edit/$id': typeof AuthedProductsEditIdRoute
  '/stock-locations/detail/$id': typeof AuthedStockLocationsDetailIdRoute
  '/stock-locations/edit/$id': typeof AuthedStockLocationsEditIdRoute
  '/units/edit/$id': typeof AuthedUnitsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_authed/categories/add': typeof AuthedCategoriesAddRoute
  '/_authed/customers/add': typeof AuthedCustomersAddRoute
  '/_authed/payment-methods/add': typeof AuthedPaymentMethodsAddRoute
  '/_authed/products/add': typeof AuthedProductsAddRoute
  '/_authed/stock-locations/add': typeof AuthedStockLocationsAddRoute
  '/_authed/units/add': typeof AuthedUnitsAddRoute
  '/_authed/categories/': typeof AuthedCategoriesIndexRoute
  '/_authed/customers/': typeof AuthedCustomersIndexRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/_authed/payment-methods/': typeof AuthedPaymentMethodsIndexRoute
  '/_authed/pos-terminal/': typeof AuthedPosTerminalIndexRoute
  '/_authed/products/': typeof AuthedProductsIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/stock-locations/': typeof AuthedStockLocationsIndexRoute
  '/_authed/stock-movements/': typeof AuthedStockMovementsIndexRoute
  '/_authed/units/': typeof AuthedUnitsIndexRoute
  '/_authed/categories/edit/$id': typeof AuthedCategoriesEditIdRoute
  '/_authed/customers/detail/$id': typeof AuthedCustomersDetailIdRoute
  '/_authed/customers/edit/$id': typeof AuthedCustomersEditIdRoute
  '/_authed/payment-methods/detail/$id': typeof AuthedPaymentMethodsDetailIdRoute
  '/_authed/payment-methods/edit/$id': typeof AuthedPaymentMethodsEditIdRoute
  '/_authed/products/detail/$id': typeof AuthedProductsDetailIdRoute
  '/_authed/products/edit/$id': typeof AuthedProductsEditIdRoute
  '/_authed/stock-locations/detail/$id': typeof AuthedStockLocationsDetailIdRoute
  '/_authed/stock-locations/edit/$id': typeof AuthedStockLocationsEditIdRoute
  '/_authed/units/edit/$id': typeof AuthedUnitsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/categories/add'
    | '/customers/add'
    | '/payment-methods/add'
    | '/products/add'
    | '/stock-locations/add'
    | '/units/add'
    | '/categories/'
    | '/customers/'
    | '/dashboard/'
    | '/payment-methods/'
    | '/pos-terminal/'
    | '/products/'
    | '/settings/'
    | '/stock-locations/'
    | '/stock-movements/'
    | '/units/'
    | '/categories/edit/$id'
    | '/customers/detail/$id'
    | '/customers/edit/$id'
    | '/payment-methods/detail/$id'
    | '/payment-methods/edit/$id'
    | '/products/detail/$id'
    | '/products/edit/$id'
    | '/stock-locations/detail/$id'
    | '/stock-locations/edit/$id'
    | '/units/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/categories/add'
    | '/customers/add'
    | '/payment-methods/add'
    | '/products/add'
    | '/stock-locations/add'
    | '/units/add'
    | '/categories'
    | '/customers'
    | '/dashboard'
    | '/payment-methods'
    | '/pos-terminal'
    | '/products'
    | '/settings'
    | '/stock-locations'
    | '/stock-movements'
    | '/units'
    | '/categories/edit/$id'
    | '/customers/detail/$id'
    | '/customers/edit/$id'
    | '/payment-methods/detail/$id'
    | '/payment-methods/edit/$id'
    | '/products/detail/$id'
    | '/products/edit/$id'
    | '/stock-locations/detail/$id'
    | '/stock-locations/edit/$id'
    | '/units/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/auth/login'
    | '/_authed/categories/add'
    | '/_authed/customers/add'
    | '/_authed/payment-methods/add'
    | '/_authed/products/add'
    | '/_authed/stock-locations/add'
    | '/_authed/units/add'
    | '/_authed/categories/'
    | '/_authed/customers/'
    | '/_authed/dashboard/'
    | '/_authed/payment-methods/'
    | '/_authed/pos-terminal/'
    | '/_authed/products/'
    | '/_authed/settings/'
    | '/_authed/stock-locations/'
    | '/_authed/stock-movements/'
    | '/_authed/units/'
    | '/_authed/categories/edit/$id'
    | '/_authed/customers/detail/$id'
    | '/_authed/customers/edit/$id'
    | '/_authed/payment-methods/detail/$id'
    | '/_authed/payment-methods/edit/$id'
    | '/_authed/products/detail/$id'
    | '/_authed/products/edit/$id'
    | '/_authed/stock-locations/detail/$id'
    | '/_authed/stock-locations/edit/$id'
    | '/_authed/units/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/units/': {
      id: '/_authed/units/'
      path: '/units'
      fullPath: '/units/'
      preLoaderRoute: typeof AuthedUnitsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/stock-movements/': {
      id: '/_authed/stock-movements/'
      path: '/stock-movements'
      fullPath: '/stock-movements/'
      preLoaderRoute: typeof AuthedStockMovementsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/stock-locations/': {
      id: '/_authed/stock-locations/'
      path: '/stock-locations'
      fullPath: '/stock-locations/'
      preLoaderRoute: typeof AuthedStockLocationsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products/': {
      id: '/_authed/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthedProductsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pos-terminal/': {
      id: '/_authed/pos-terminal/'
      path: '/pos-terminal'
      fullPath: '/pos-terminal/'
      preLoaderRoute: typeof AuthedPosTerminalIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/payment-methods/': {
      id: '/_authed/payment-methods/'
      path: '/payment-methods'
      fullPath: '/payment-methods/'
      preLoaderRoute: typeof AuthedPaymentMethodsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/customers/': {
      id: '/_authed/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthedCustomersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/categories/': {
      id: '/_authed/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof AuthedCategoriesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/units/add': {
      id: '/_authed/units/add'
      path: '/units/add'
      fullPath: '/units/add'
      preLoaderRoute: typeof AuthedUnitsAddRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/stock-locations/add': {
      id: '/_authed/stock-locations/add'
      path: '/stock-locations/add'
      fullPath: '/stock-locations/add'
      preLoaderRoute: typeof AuthedStockLocationsAddRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products/add': {
      id: '/_authed/products/add'
      path: '/products/add'
      fullPath: '/products/add'
      preLoaderRoute: typeof AuthedProductsAddRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/payment-methods/add': {
      id: '/_authed/payment-methods/add'
      path: '/payment-methods/add'
      fullPath: '/payment-methods/add'
      preLoaderRoute: typeof AuthedPaymentMethodsAddRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/customers/add': {
      id: '/_authed/customers/add'
      path: '/customers/add'
      fullPath: '/customers/add'
      preLoaderRoute: typeof AuthedCustomersAddRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/categories/add': {
      id: '/_authed/categories/add'
      path: '/categories/add'
      fullPath: '/categories/add'
      preLoaderRoute: typeof AuthedCategoriesAddRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/units/edit/$id': {
      id: '/_authed/units/edit/$id'
      path: '/units/edit/$id'
      fullPath: '/units/edit/$id'
      preLoaderRoute: typeof AuthedUnitsEditIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/stock-locations/edit/$id': {
      id: '/_authed/stock-locations/edit/$id'
      path: '/stock-locations/edit/$id'
      fullPath: '/stock-locations/edit/$id'
      preLoaderRoute: typeof AuthedStockLocationsEditIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/stock-locations/detail/$id': {
      id: '/_authed/stock-locations/detail/$id'
      path: '/stock-locations/detail/$id'
      fullPath: '/stock-locations/detail/$id'
      preLoaderRoute: typeof AuthedStockLocationsDetailIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products/edit/$id': {
      id: '/_authed/products/edit/$id'
      path: '/products/edit/$id'
      fullPath: '/products/edit/$id'
      preLoaderRoute: typeof AuthedProductsEditIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products/detail/$id': {
      id: '/_authed/products/detail/$id'
      path: '/products/detail/$id'
      fullPath: '/products/detail/$id'
      preLoaderRoute: typeof AuthedProductsDetailIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/payment-methods/edit/$id': {
      id: '/_authed/payment-methods/edit/$id'
      path: '/payment-methods/edit/$id'
      fullPath: '/payment-methods/edit/$id'
      preLoaderRoute: typeof AuthedPaymentMethodsEditIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/payment-methods/detail/$id': {
      id: '/_authed/payment-methods/detail/$id'
      path: '/payment-methods/detail/$id'
      fullPath: '/payment-methods/detail/$id'
      preLoaderRoute: typeof AuthedPaymentMethodsDetailIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/customers/edit/$id': {
      id: '/_authed/customers/edit/$id'
      path: '/customers/edit/$id'
      fullPath: '/customers/edit/$id'
      preLoaderRoute: typeof AuthedCustomersEditIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/customers/detail/$id': {
      id: '/_authed/customers/detail/$id'
      path: '/customers/detail/$id'
      fullPath: '/customers/detail/$id'
      preLoaderRoute: typeof AuthedCustomersDetailIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/categories/edit/$id': {
      id: '/_authed/categories/edit/$id'
      path: '/categories/edit/$id'
      fullPath: '/categories/edit/$id'
      preLoaderRoute: typeof AuthedCategoriesEditIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedCategoriesAddRoute: typeof AuthedCategoriesAddRoute
  AuthedCustomersAddRoute: typeof AuthedCustomersAddRoute
  AuthedPaymentMethodsAddRoute: typeof AuthedPaymentMethodsAddRoute
  AuthedProductsAddRoute: typeof AuthedProductsAddRoute
  AuthedStockLocationsAddRoute: typeof AuthedStockLocationsAddRoute
  AuthedUnitsAddRoute: typeof AuthedUnitsAddRoute
  AuthedCategoriesIndexRoute: typeof AuthedCategoriesIndexRoute
  AuthedCustomersIndexRoute: typeof AuthedCustomersIndexRoute
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
  AuthedPaymentMethodsIndexRoute: typeof AuthedPaymentMethodsIndexRoute
  AuthedPosTerminalIndexRoute: typeof AuthedPosTerminalIndexRoute
  AuthedProductsIndexRoute: typeof AuthedProductsIndexRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
  AuthedStockLocationsIndexRoute: typeof AuthedStockLocationsIndexRoute
  AuthedStockMovementsIndexRoute: typeof AuthedStockMovementsIndexRoute
  AuthedUnitsIndexRoute: typeof AuthedUnitsIndexRoute
  AuthedCategoriesEditIdRoute: typeof AuthedCategoriesEditIdRoute
  AuthedCustomersDetailIdRoute: typeof AuthedCustomersDetailIdRoute
  AuthedCustomersEditIdRoute: typeof AuthedCustomersEditIdRoute
  AuthedPaymentMethodsDetailIdRoute: typeof AuthedPaymentMethodsDetailIdRoute
  AuthedPaymentMethodsEditIdRoute: typeof AuthedPaymentMethodsEditIdRoute
  AuthedProductsDetailIdRoute: typeof AuthedProductsDetailIdRoute
  AuthedProductsEditIdRoute: typeof AuthedProductsEditIdRoute
  AuthedStockLocationsDetailIdRoute: typeof AuthedStockLocationsDetailIdRoute
  AuthedStockLocationsEditIdRoute: typeof AuthedStockLocationsEditIdRoute
  AuthedUnitsEditIdRoute: typeof AuthedUnitsEditIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCategoriesAddRoute: AuthedCategoriesAddRoute,
  AuthedCustomersAddRoute: AuthedCustomersAddRoute,
  AuthedPaymentMethodsAddRoute: AuthedPaymentMethodsAddRoute,
  AuthedProductsAddRoute: AuthedProductsAddRoute,
  AuthedStockLocationsAddRoute: AuthedStockLocationsAddRoute,
  AuthedUnitsAddRoute: AuthedUnitsAddRoute,
  AuthedCategoriesIndexRoute: AuthedCategoriesIndexRoute,
  AuthedCustomersIndexRoute: AuthedCustomersIndexRoute,
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
  AuthedPaymentMethodsIndexRoute: AuthedPaymentMethodsIndexRoute,
  AuthedPosTerminalIndexRoute: AuthedPosTerminalIndexRoute,
  AuthedProductsIndexRoute: AuthedProductsIndexRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
  AuthedStockLocationsIndexRoute: AuthedStockLocationsIndexRoute,
  AuthedStockMovementsIndexRoute: AuthedStockMovementsIndexRoute,
  AuthedUnitsIndexRoute: AuthedUnitsIndexRoute,
  AuthedCategoriesEditIdRoute: AuthedCategoriesEditIdRoute,
  AuthedCustomersDetailIdRoute: AuthedCustomersDetailIdRoute,
  AuthedCustomersEditIdRoute: AuthedCustomersEditIdRoute,
  AuthedPaymentMethodsDetailIdRoute: AuthedPaymentMethodsDetailIdRoute,
  AuthedPaymentMethodsEditIdRoute: AuthedPaymentMethodsEditIdRoute,
  AuthedProductsDetailIdRoute: AuthedProductsDetailIdRoute,
  AuthedProductsEditIdRoute: AuthedProductsEditIdRoute,
  AuthedStockLocationsDetailIdRoute: AuthedStockLocationsDetailIdRoute,
  AuthedStockLocationsEditIdRoute: AuthedStockLocationsEditIdRoute,
  AuthedUnitsEditIdRoute: AuthedUnitsEditIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
